<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="4116" started-at="2022-02-18T16:00:24 IST" finished-at="2022-02-18T16:00:28 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="4116" started-at="2022-02-18T16:00:24 IST" finished-at="2022-02-18T16:00:28 IST">
      <class name="restapi.VerifyProfile">
        <test-method status="FAIL" signature="verifyRegisterdProfile()[pri:0, instance:restapi.VerifyProfile@42f93a98]" name="verifyRegisterdProfile" duration-ms="953" started-at="2022-02-18T16:00:27 IST" depends-on-methods="restapi.LoginUIBank.loginUiBankMethod" finished-at="2022-02-18T16:00:28 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [jsiri90@gmail.com1] but found [[jsiri90@gmail.com]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [jsiri90@gmail.com1] but found [[jsiri90@gmail.com]]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:563)
at restapi.VerifyProfile.verifyRegisterdProfile(VerifyProfile.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyRegisterdProfile -->
      </class> <!-- restapi.VerifyProfile -->
      <class name="restapi.LoginUIBank">
        <test-method status="PASS" signature="loginUiBankMethod()[pri:0, instance:restapi.LoginUIBank@c46bcd4]" name="loginUiBankMethod" duration-ms="3133" started-at="2022-02-18T16:00:24 IST" finished-at="2022-02-18T16:00:27 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginUiBankMethod -->
      </class> <!-- restapi.LoginUIBank -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
